######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 23 07:43:05 2015
######################################################################
include(../../qtscript/)
TEMPLATE = app
TARGET = 
DEPENDPATH += . ../../include
INCLUDEPATH += . ../../include

# Input
SOURCES += main.cpp
