######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 23 07:43:05 2015
######################################################################
include(../../qtscript/common_static.pri)
TEMPLATE = app
TARGET = 
DEPENDPATH += . ../../include ../
INCLUDEPATH += . ../../include ../

config += console

# Input
SOURCES += main.cpp
