######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 23 07:43:30 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
